### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by jojo2234** [webshield-dev/eudvcdecoder#11]
Hello, on my account I've setted up a repository with the public keys and now I'm trying to implement the verification step, if you are interested here is the link: 

https://github.com/jojo2234/GreenPassHack/

I've read about your legal doubts, I think it is legal get the public keys, you can have trouble if you get the private key of a person without his/her consensus. Public Keys are downloaded in personal phones of many people and are secure, I means you are not able to identify the person from his/her public key.

**Comment by maslick** [comment]
In addition, the public keys belong to Health institutions that sign COVID certificates (using their private keys), and NOT to people. Public keys are meant to verify the signature, so they are public and can (and should) be shared with the public.

**Comment by jojo2234** [comment]
I'm sorry I was thinking this issue was closed the link I've posted it's a bit old.
